/**
 * Profile completeness utilities
 *
 * Extracted from AuthContext so the logic is testable independently.
 * The auto-generated display name pattern (Worker_XXXXXXXX) is a sentinel
 * created by get_or_create_executor — it does NOT count as a real profile.
 */

/**
 * Pattern matching auto-generated display names from get_or_create_executor.
 * Format: "Worker_" followed by exactly 8 hex characters (from wallet address slice).
 * Examples: Worker_2b50111b, Worker_e4dc963c, Worker_AABBCCDD
 */
export const AUTO_GENERATED_NAME_PATTERN = /^Worker_[0-9a-f]{8}$/i

/**
 * Check if a display name is auto-generated (not user-chosen).
 */
export function isAutoGeneratedName(name: string | null | undefined): boolean {
  if (!name) return true
  return AUTO_GENERATED_NAME_PATTERN.test(name)
}

/**
 * Determine if an executor's profile is complete enough to skip onboarding.
 *
 * A profile is complete when the user has explicitly set their display name
 * (i.e. it's not null/empty AND not an auto-generated Worker_XXXX pattern).
 *
 * This is the SINGLE SOURCE OF TRUTH for profile completeness.
 * Both AuthContext and ProfileCompletionModal should use this function.
 */
export function checkProfileComplete(
  executor: { display_name?: string | null } | null | undefined
): boolean {
  if (!executor) return false
  if (!executor.display_name) return false
  if (isAutoGeneratedName(executor.display_name)) return false
  return true
}
