/**
 * AuthContext — Unit tests for pure logic and derived state.
 *
 * The AuthContext is tightly coupled to Dynamic.xyz SDK hooks and Supabase,
 * so we test the exported pure helpers and state derivation logic that can
 * be exercised without rendering the full provider.
 */

import { describe, it, expect } from 'vitest'
import { checkProfileComplete, isAutoGeneratedName } from '../../utils/profileUtils'

// --------------------------------------------------------------------------
// isAuthenticated derivation logic
// --------------------------------------------------------------------------

describe('AuthContext derived state logic', () => {
  // The isAuthenticated formula from AuthContext:
  // isAuthenticated = dynamicInitialized && isLoggedIn && !!dynamicWalletAddress
  const deriveIsAuthenticated = (
    dynamicInitialized: boolean,
    isLoggedIn: boolean,
    dynamicWalletAddress: string | null
  ) => dynamicInitialized && isLoggedIn && !!dynamicWalletAddress

  it('is not authenticated before Dynamic SDK initializes', () => {
    expect(deriveIsAuthenticated(false, true, '0xabc')).toBe(false)
  })

  it('is not authenticated when logged out', () => {
    expect(deriveIsAuthenticated(true, false, '0xabc')).toBe(false)
  })

  it('is not authenticated without a wallet address', () => {
    expect(deriveIsAuthenticated(true, true, null)).toBe(false)
  })

  it('is authenticated with all conditions met', () => {
    expect(deriveIsAuthenticated(true, true, '0xabc123')).toBe(true)
  })
})

// --------------------------------------------------------------------------
// isProfileComplete (delegates to shared profileUtils, but AuthContext
// applies it — ensure the integration works)
// --------------------------------------------------------------------------

describe('AuthContext isProfileComplete', () => {
  it('returns false for null executor', () => {
    expect(checkProfileComplete(null)).toBe(false)
  })

  it('returns false for auto-generated name', () => {
    expect(
      checkProfileComplete({
        id: '1',
        display_name: 'Worker_2b50111b',
        wallet_address: '0xabc',
      } as any)
    ).toBe(false)
  })

  it('returns true for manually set name', () => {
    expect(
      checkProfileComplete({
        id: '1',
        display_name: 'Maria',
        wallet_address: '0xabc',
      } as any)
    ).toBe(true)
  })
})

// --------------------------------------------------------------------------
// E2E escape hatch
// --------------------------------------------------------------------------

describe('E2E escape hatch (window.__E2E_AUTH__)', () => {
  it('window.__E2E_AUTH__ is undefined by default', () => {
    expect(window.__E2E_AUTH__).toBeUndefined()
  })

  it('can set and read E2E auth state', () => {
    window.__E2E_AUTH__ = {
      isAuthenticated: true,
      walletAddress: '0xtest',
      userId: 'test-user',
      role: 'worker',
    }
    expect(window.__E2E_AUTH__?.isAuthenticated).toBe(true)
    expect(window.__E2E_AUTH__?.walletAddress).toBe('0xtest')
    // Cleanup
    delete window.__E2E_AUTH__
  })
})

// --------------------------------------------------------------------------
// isAbortError (extracted logic from AuthContext)
// --------------------------------------------------------------------------

describe('isAbortError detection', () => {
  const isAbortError = (err: unknown): boolean => {
    if (!err || typeof err !== 'object') return false
    const message = (err as { message?: string }).message || ''
    return message.includes('AbortError') || message.includes('signal is aborted')
  }

  it('detects AbortError', () => {
    expect(isAbortError(new DOMException('AbortError'))).toBe(true)
  })

  it('detects signal is aborted', () => {
    expect(isAbortError(new Error('The signal is aborted'))).toBe(true)
  })

  it('rejects null', () => {
    expect(isAbortError(null)).toBe(false)
  })

  it('rejects non-abort errors', () => {
    expect(isAbortError(new Error('Network error'))).toBe(false)
  })

  it('rejects primitives', () => {
    expect(isAbortError('AbortError')).toBe(false)
  })
})

// --------------------------------------------------------------------------
// Storage key constants
// --------------------------------------------------------------------------

describe('storage key conventions', () => {
  it('user type key starts with em_ prefix', () => {
    // These match the constants in AuthContext.tsx
    expect('em_user_type').toMatch(/^em_/)
  })

  it('wallet key starts with em_ prefix', () => {
    expect('em_last_wallet_address').toMatch(/^em_/)
  })
})
