/**
 * Profile Completeness Tests
 *
 * These tests prevent the onboarding regression where auto-generated
 * display names (Worker_XXXXXXXX) caused isProfileComplete to be always true,
 * hiding the ProfileCompletionModal from new users.
 *
 * Incident: Feb 16, 2026 — get_or_create_executor auto-generates "Worker_XXXX"
 * names, so `!!executor.display_name` was always truthy. New users never saw
 * the onboarding form.
 *
 * @see https://github.com/UltravioletaDAO/execution-market/commit/abc592a
 */

import { describe, it, expect } from 'vitest'
import {
  checkProfileComplete,
  isAutoGeneratedName,
  AUTO_GENERATED_NAME_PATTERN,
} from '../../utils/profileUtils'

// ============================================================================
// isAutoGeneratedName
// ============================================================================

describe('isAutoGeneratedName', () => {
  describe('detects auto-generated Worker_XXXX names', () => {
    it('matches Worker_ + 8 hex lowercase', () => {
      expect(isAutoGeneratedName('Worker_2b50111b')).toBe(true)
    })

    it('matches Worker_ + 8 hex uppercase', () => {
      expect(isAutoGeneratedName('Worker_AABBCCDD')).toBe(true)
    })

    it('matches Worker_ + 8 hex mixed case', () => {
      expect(isAutoGeneratedName('Worker_e4Dc963C')).toBe(true)
    })

    it('matches Worker_ + all zeros', () => {
      expect(isAutoGeneratedName('Worker_00000000')).toBe(true)
    })

    it('matches Worker_ + all f', () => {
      expect(isAutoGeneratedName('Worker_ffffffff')).toBe(true)
    })

    it('matches Worker_ + all F', () => {
      expect(isAutoGeneratedName('Worker_FFFFFFFF')).toBe(true)
    })
  })

  describe('rejects real user names', () => {
    it('rejects normal name', () => {
      expect(isAutoGeneratedName('Maria Garcia')).toBe(false)
    })

    it('rejects single word name', () => {
      expect(isAutoGeneratedName('0xultravioleta')).toBe(false)
    })

    it('rejects name starting with Worker but different format', () => {
      expect(isAutoGeneratedName('Worker Man')).toBe(false)
    })

    it('rejects Worker_ with too few hex chars (7)', () => {
      expect(isAutoGeneratedName('Worker_2b5011b')).toBe(false)
    })

    it('rejects Worker_ with too many hex chars (9)', () => {
      expect(isAutoGeneratedName('Worker_2b50111b0')).toBe(false)
    })

    it('rejects Worker_ with non-hex chars', () => {
      expect(isAutoGeneratedName('Worker_2b50ghij')).toBe(false)
    })

    it('rejects lowercase worker_ prefix', () => {
      // Pattern is case-insensitive on hex, but Worker_ prefix must match /^Worker_/i
      // So "worker_2b50111b" DOES match (case insensitive flag)
      // This is correct behavior — the DB might store it differently
      expect(isAutoGeneratedName('worker_2b50111b')).toBe(true)
    })

    it('rejects Worker_ with spaces', () => {
      expect(isAutoGeneratedName('Worker_ 2b50111')).toBe(false)
    })

    it('rejects empty-ish names that contain Worker_ inside', () => {
      expect(isAutoGeneratedName('My Worker_2b50111b name')).toBe(false)
    })
  })

  describe('handles null/undefined/empty', () => {
    it('null is auto-generated (no real name)', () => {
      expect(isAutoGeneratedName(null)).toBe(true)
    })

    it('undefined is auto-generated', () => {
      expect(isAutoGeneratedName(undefined)).toBe(true)
    })

    it('empty string is auto-generated', () => {
      expect(isAutoGeneratedName('')).toBe(true)
    })
  })
})

// ============================================================================
// checkProfileComplete
// ============================================================================

describe('checkProfileComplete', () => {
  describe('returns false for incomplete profiles', () => {
    it('null executor', () => {
      expect(checkProfileComplete(null)).toBe(false)
    })

    it('undefined executor', () => {
      expect(checkProfileComplete(undefined)).toBe(false)
    })

    it('executor with null display_name', () => {
      expect(checkProfileComplete({ display_name: null })).toBe(false)
    })

    it('executor with undefined display_name', () => {
      expect(checkProfileComplete({ display_name: undefined })).toBe(false)
    })

    it('executor with empty display_name', () => {
      expect(checkProfileComplete({ display_name: '' })).toBe(false)
    })

    it('executor with auto-generated Worker_XXXX name', () => {
      expect(checkProfileComplete({ display_name: 'Worker_2b50111b' })).toBe(false)
    })

    it('executor with uppercase auto-generated name', () => {
      expect(checkProfileComplete({ display_name: 'Worker_AABB1122' })).toBe(false)
    })
  })

  describe('returns true for complete profiles', () => {
    it('executor with real name', () => {
      expect(checkProfileComplete({ display_name: '0xultravioleta' })).toBe(true)
    })

    it('executor with multi-word name', () => {
      expect(checkProfileComplete({ display_name: 'Maria Garcia' })).toBe(true)
    })

    it('executor with simple name', () => {
      expect(checkProfileComplete({ display_name: 'FastRunner' })).toBe(true)
    })

    it('executor with emoji name', () => {
      expect(checkProfileComplete({ display_name: '🦞 Clawd' })).toBe(true)
    })

    it('executor with number-only name (user chose it)', () => {
      expect(checkProfileComplete({ display_name: '12345678' })).toBe(true)
    })

    it('executor named Worker (no underscore + hex)', () => {
      expect(checkProfileComplete({ display_name: 'Worker' })).toBe(true)
    })

    it('executor named Worker_something_else', () => {
      expect(checkProfileComplete({ display_name: 'Worker_MyName' })).toBe(true)
    })
  })

  describe('regression: the original bug scenario', () => {
    it('new user created by get_or_create_executor should NOT be complete', () => {
      // This is the EXACT scenario that caused the bug:
      // get_or_create_executor generates: Worker_ + first 8 chars of wallet address
      const walletAddress = '0xe4dc963c56979e0260fc146b87ee24f18220e545'
      const autoName = `Worker_${walletAddress.slice(2, 10)}`
      // autoName = "Worker_e4dc963c"

      expect(autoName).toBe('Worker_e4dc963c')
      expect(checkProfileComplete({ display_name: autoName })).toBe(false)
    })

    it('user who completed onboarding should be complete', () => {
      expect(checkProfileComplete({ display_name: '0xultravioleta' })).toBe(true)
    })

    it('Golden Flow Test Worker (real test account) should be complete', () => {
      expect(checkProfileComplete({ display_name: 'Golden Flow Test Worker' })).toBe(true)
    })
  })
})

// ============================================================================
// AUTO_GENERATED_NAME_PATTERN regex sanity
// ============================================================================

describe('AUTO_GENERATED_NAME_PATTERN', () => {
  it('is case insensitive', () => {
    expect(AUTO_GENERATED_NAME_PATTERN.flags).toContain('i')
  })

  it('anchored at start and end', () => {
    expect(AUTO_GENERATED_NAME_PATTERN.source).toMatch(/^\^/)
    expect(AUTO_GENERATED_NAME_PATTERN.source).toMatch(/\$$/)
  })
})
