#!/bin/bash
# =============================================================================
# release-notes.sh — Generate release notes for Execution Market deploys
# =============================================================================
#
# Usage:
#   ./release-notes.sh                    # Since last tag
#   ./release-notes.sh v0.1.0..HEAD       # Custom range
#   ./release-notes.sh --since "2 days"   # Time-based
#
# Output: Markdown-formatted release notes to stdout
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

# Parse args
RANGE=""
SINCE=""

for arg in "$@"; do
  case $arg in
    --since)
      shift
      SINCE="$1"
      shift
      ;;
    --help|-h)
      echo "Usage: $0 [range] [--since \"N days\"]"
      exit 0
      ;;
    *)
      RANGE="$arg"
      ;;
  esac
done

# Determine git range
if [ -n "$SINCE" ]; then
  RANGE="$(git log --since="$SINCE" --format='%H' | tail -1)..HEAD"
elif [ -z "$RANGE" ]; then
  LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
  if [ -n "$LAST_TAG" ]; then
    RANGE="${LAST_TAG}..HEAD"
  else
    RANGE="$(git log --oneline -20 | tail -1 | cut -d' ' -f1)..HEAD"
  fi
fi

# Gather info
GIT_SHA=$(git rev-parse --short=8 HEAD)
GIT_BRANCH=$(git branch --show-current)
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
COMMIT_COUNT=$(git log "$RANGE" --oneline 2>/dev/null | wc -l | tr -d ' ')

# Generate notes
cat <<NOTES
# Release Notes — Execution Market

**Date:** ${TIMESTAMP}
**Commit:** \`${GIT_SHA}\` (${GIT_BRANCH})
**Commits in release:** ${COMMIT_COUNT}

## Changes

$(git log "$RANGE" --pretty=format:"- %s (\`%h\`)" 2>/dev/null)

## Services Deployed

| Service | URL | Image Tag |
|---------|-----|-----------|
| Dashboard | https://execution.market | \`${GIT_SHA}\` |
| MCP Server | https://mcp.execution.market | \`${GIT_SHA}\` |
| API | https://api.execution.market | \`${GIT_SHA}\` |

## Infrastructure

| Component | Status |
|-----------|--------|
| Evidence Lambda | https://vhvwpq0lu0.execute-api.us-east-2.amazonaws.com |
| Evidence CDN | https://d3h6yzj24t9k8z.cloudfront.net |
| S3 Bucket | em-production-evidence-518898403364 |

## Post-Deploy Verification

- [ ] \`curl https://api.execution.market/health\` returns healthy
- [ ] \`curl https://api.execution.market/health/sanity\` returns ok
- [ ] \`curl https://execution.market\` loads dashboard
- [ ] \`curl https://mcp.execution.market/.well-known/agent.json\` returns agent card

## On-Chain Evidence

| Transaction | Network | Hash |
|-------------|---------|------|
| _No on-chain transactions in this release_ | | |

---
*Generated by \`release-notes.sh\` at ${TIMESTAMP}*
NOTES
