/**
 * Execution Market: Authentication Context (Dynamic.xyz Integration)
 *
 * Provides authentication state using Dynamic.xyz for wallet auth
 * and Supabase for executor data storage.
 */

import {
  createContext,
  useState,
  useEffect,
  useCallback,
  useRef,
  type ReactNode,
} from 'react'
import { useDynamicContext, useIsLoggedIn, useUserWallets } from '@dynamic-labs/sdk-react-core'
import { supabase } from '../lib/supabase'
import type { Executor } from '../types/database'
import { checkProfileComplete, isAutoGeneratedName } from '../utils/profileUtils'
import { useXProfileEnrichment } from '../hooks/useXProfileEnrichment'
import { clearAgentSession } from '../utils/agentAuth'
import { clearAuthToken } from '../services/api'
import i18nInstance, { getCurrentLanguage, type SupportedLanguage, SUPPORTED_LANGUAGES } from '../i18n'

// --------------------------------------------------------------------------
// Types
// --------------------------------------------------------------------------

export type UserType = 'worker' | 'agent' | null

// --------------------------------------------------------------------------
// E2E Test Escape Hatch
// --------------------------------------------------------------------------

interface E2EAuthState {
  isAuthenticated: boolean
  walletAddress: string
  userId: string
  role: UserType
  displayName?: string
}

declare global {
  interface Window {
    __E2E_AUTH__?: E2EAuthState
  }
}

interface AuthContextValue {
  // State
  walletAddress: string | null
  executor: Executor | null
  userType: UserType
  isAuthenticated: boolean
  isProfileComplete: boolean
  loading: boolean
  error: Error | null

  // Actions
  logout: () => Promise<void>
  setUserType: (type: UserType) => void
  refreshExecutor: () => Promise<void>
  openAuthModal: () => void
}

// --------------------------------------------------------------------------
// Constants
// --------------------------------------------------------------------------

const USER_TYPE_STORAGE_KEY = 'em_user_type'
const WALLET_STORAGE_KEY = 'em_last_wallet_address'

const isAbortError = (err: unknown): boolean => {
  if (!err || typeof err !== 'object') return false
  const message = (err as { message?: string }).message || ''
  return message.includes('AbortError') || message.includes('signal is aborted')
}

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

// --------------------------------------------------------------------------
// Context
// --------------------------------------------------------------------------

const AuthContext = createContext<AuthContextValue | undefined>(undefined)

// Export context for use in hooks
export { AuthContext }
export type { AuthContextValue }

// --------------------------------------------------------------------------
// Provider Component
// --------------------------------------------------------------------------

interface AuthProviderProps {
  children: ReactNode
}

export function AuthProvider({ children }: AuthProviderProps) {
  const { primaryWallet, handleLogOut, setShowAuthFlow, sdkHasLoaded, user } = useDynamicContext()
  const isLoggedIn = useIsLoggedIn()
  const userWallets = useUserWallets()
  const { enrichFromX } = useXProfileEnrichment()

  const [executor, setExecutor] = useState<Executor | null>(null)
  const [userType, setUserTypeState] = useState<UserType>(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem(USER_TYPE_STORAGE_KEY)
      if (stored === 'worker' || stored === 'agent') {
        return stored
      }
    }
    return null
  })
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<Error | null>(null)
  const [dynamicInitialized, setDynamicInitialized] = useState(false)
  const [persistedWalletAddress, setPersistedWalletAddress] = useState<string | null>(() => {
    if (typeof window === 'undefined') return null
    const stored = localStorage.getItem(WALLET_STORAGE_KEY)
    return stored ? stored.toLowerCase() : null
  })
  const lastWalletRef = useRef<string | null>(null)
  const linkedWalletRef = useRef<string | null>(null)
  const linkingRef = useRef(false)
  const logoutDebounceRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const loadingTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  // Ref for dynamicWalletAddress — avoids it being an effect dependency
  // which caused unnecessary re-fetches when Dynamic SDK transitions wallet state
  const dynamicWalletRef = useRef<string | null>(null)

  // Derived state
  // FIX: When user logs in via email, Dynamic SDK creates an embedded wallet and
  // selects it as primaryWallet. We prefer the user's own (non-embedded) wallet
  // over the auto-generated embedded one. Fallback to primaryWallet if no
  // non-embedded wallets exist (e.g. email-only users with only an embedded wallet).
  const preferredWallet = ((): typeof primaryWallet => {
    if (!primaryWallet) return null
    // If primaryWallet is not embedded, use it directly (most common case)
    if (!primaryWallet.connector?.isEmbeddedWallet) return primaryWallet
    // primaryWallet is embedded — look for a non-embedded alternative
    const nonEmbedded = userWallets.find(w => w.address && !w.connector?.isEmbeddedWallet)
    if (nonEmbedded) {
      console.log('[Auth] Preferring non-embedded wallet over embedded:', nonEmbedded.address)
      return nonEmbedded
    }
    // Only embedded wallets available — use primaryWallet as-is
    return primaryWallet
  })()
  const dynamicWalletAddress = preferredWallet?.address?.toLowerCase() || null
  dynamicWalletRef.current = dynamicWalletAddress
  // After SDK init, only trust SDK wallet. Persisted wallet is a pre-init hint
  // to avoid flash of unauthenticated content, but must NOT be used for executor
  // lookups once SDK is initialized — the SDK is the source of truth.
  const walletAddress = dynamicInitialized
    ? dynamicWalletAddress
    : (dynamicWalletAddress || persistedWalletAddress || null)
  // Only consider authenticated when Dynamic SDK says user is logged in.
  // persistedWalletAddress is a hint for executor lookup, NOT an auth signal.
  const isAuthenticated = dynamicInitialized && isLoggedIn
  // Profile is complete only when the user has explicitly set their display name.
  // Auto-generated names like "Worker_2b50111b" do NOT count as complete — the
  // onboarding form must appear so the user fills in their real info.
  // Uses the shared utility so the logic is tested independently (see profileUtils.test.ts).
  const isProfileComplete = checkProfileComplete(executor)

  // --------------------------------------------------------------------------
  // Ensure we have a Supabase session (anonymous) so RLS can resolve auth.uid()
  // --------------------------------------------------------------------------
  const ensureSupabaseSession = useCallback(async () => {
    const { data: sessionData } = await supabase.auth.getSession()
    if (sessionData.session?.user) {
      return sessionData.session.user
    }

    const { data, error: authError } = await supabase.auth.signInAnonymously()
    if (authError) {
      throw authError
    }

    return data.user
  }, [])

  // --------------------------------------------------------------------------
  // Link wallet to Supabase session (security definer RPC, supports anon users)
  // --------------------------------------------------------------------------
  const linkWalletToSession = useCallback(async (wallet: string) => {
    if (linkingRef.current || linkedWalletRef.current === wallet) {
      return
    }

    linkingRef.current = true
    try {
      const user = await ensureSupabaseSession()
      if (!user) return

      const { error: linkError } = await supabase.rpc('link_wallet_to_session', {
        p_user_id: user.id,
        p_wallet_address: wallet,
      })

      if (linkError) {
        console.warn('[Auth] link_wallet_to_session error:', linkError)
        console.warn('[Auth] link_wallet_to_session error details:', {
          code: (linkError as { code?: string }).code,
          message: (linkError as { message?: string }).message,
          details: (linkError as { details?: string }).details,
          hint: (linkError as { hint?: string }).hint,
        })
      } else {
        linkedWalletRef.current = wallet
      }
    } catch (err) {
      console.warn('[Auth] Failed to link wallet to session:', err)
    } finally {
      linkingRef.current = false
    }
  }, [ensureSupabaseSession])

  // --------------------------------------------------------------------------
  // Fetch or create executor using RPC function (bypasses RLS)
  // --------------------------------------------------------------------------
  const fetchExecutor = useCallback(async (wallet: string, email?: string | null): Promise<Executor | null> => {
    const normalizedWallet = wallet.toLowerCase()

    try {
      const rpcCall = async () => supabase.rpc('get_or_create_executor', {
        p_wallet_address: normalizedWallet,
        p_display_name: null,
        p_email: email || null,
      })

      let { data, error } = await rpcCall()
      if (error && isAbortError(error)) {
        await delay(250)
        const retry = await rpcCall()
        data = retry.data
        error = retry.error
      }

      if (error) {
        console.error('[Auth] get_or_create_executor error:', error)

        // Fallback: try to load executor directly by wallet
        const { data: existing, error: existingError } = await supabase
          .from('executors')
          .select('*')
          .eq('wallet_address', normalizedWallet)
          .maybeSingle()

        if (existingError) {
          console.error('[Auth] Fallback executor lookup error:', existingError)
        }

        if (existing) {
          return existing as Executor
        }

        // Last resort: attempt to create executor directly (requires authenticated role)
        const { data: sessionData } = await supabase.auth.getSession()
        const sessionUser = sessionData.session?.user

        if (sessionUser) {
          const displayName = `Worker_${normalizedWallet.slice(2, 10)}`
          const { data: inserted, error: insertError } = await supabase
            .from('executors')
            .insert({
              wallet_address: normalizedWallet,
              user_id: sessionUser.id,
              display_name: displayName,
              email: null,
            })
            .select('*')
            .single()

          if (insertError) {
            console.error('[Auth] Fallback executor insert error:', insertError)
          } else if (inserted) {
            return inserted as Executor
          }
        }

        return null
      }

      // RPC returns an array, get first element
      const executorData = Array.isArray(data) ? data[0] : data
      if (!executorData) {
        console.error('[Auth] No executor data returned')
        return null
      }

      // Fetch full executor profile for complete fields
      const { data: fullExecutor, error: fullError } = await supabase
        .from('executors')
        .select('*')
        .eq('id', executorData.id)
        .maybeSingle()

      if (fullExecutor && !fullError) {
        console.log('[Auth] Executor loaded:', fullExecutor.id, 'isNew:', executorData.is_new)
        return fullExecutor as Executor
      }

      if (fullError) {
        console.warn('[Auth] Executor full fetch failed, using RPC data:', fullError)
      }

      console.log('[Auth] Executor loaded (RPC only):', executorData.id, 'isNew:', executorData.is_new)

      // Map RPC response to Executor type (fallback)
      return {
        id: executorData.id,
        user_id: null,
        wallet_address: executorData.wallet_address,
        display_name: executorData.display_name,
        bio: null,
        avatar_url: null,
        skills: [],
        languages: [],
        roles: [],
        email: executorData.email,
        phone: null,
        default_location: null,
        location_city: null,
        location_country: null,
        reputation_score: executorData.reputation_score,
        tasks_completed: executorData.tasks_completed,
        tasks_disputed: 0,
        tasks_abandoned: 0,
        avg_rating: null,
        reputation_contract: null,
        reputation_token_id: null,
        erc8004_agent_id: null,
        agent_type: 'human' as const,
        networks_active: [],
        social_links: null,
        world_id_verified: false,
        world_id_level: null,
        world_human_id: null,
        world_verified_at: null,
        created_at: executorData.created_at,
        updated_at: executorData.created_at,
        last_active_at: null,
      } as Executor
    } catch (err) {
      console.error('[Auth] fetchExecutor exception:', err)
      setError(err instanceof Error ? err : new Error('Failed to load profile'))
      return null
    }
  }, [])

  // --------------------------------------------------------------------------
  // Set user type (persisted to localStorage)
  // --------------------------------------------------------------------------
  const setUserType = useCallback((type: UserType) => {
    setUserTypeState(type)
    if (typeof window !== 'undefined') {
      if (type) {
        localStorage.setItem(USER_TYPE_STORAGE_KEY, type)
      } else {
        localStorage.removeItem(USER_TYPE_STORAGE_KEY)
      }
    }
  }, [])

  // --------------------------------------------------------------------------
  // Refresh executor data
  // --------------------------------------------------------------------------
  const refreshExecutor = useCallback(async () => {
    if (!walletAddress) return
    await linkWalletToSession(walletAddress)
    const executorData = await fetchExecutor(walletAddress, user?.email)
    setExecutor(executorData)
  }, [walletAddress, fetchExecutor, linkWalletToSession, user])

  // --------------------------------------------------------------------------
  // Logout
  // --------------------------------------------------------------------------
  const logout = useCallback(async () => {
    // Cancel any pending timeouts to prevent state updates after logout
    if (loadingTimeoutRef.current) {
      clearTimeout(loadingTimeoutRef.current)
      loadingTimeoutRef.current = null
    }
    if (logoutDebounceRef.current) {
      clearTimeout(logoutDebounceRef.current)
      logoutDebounceRef.current = null
    }

    await handleLogOut()
    setExecutor(null)
    setUserType(null)
    setError(null)
    setPersistedWalletAddress(null)
    localStorage.removeItem(WALLET_STORAGE_KEY)
    // FE-009: Clear all auth tokens on logout to prevent stale credentials
    clearAgentSession()
    clearAuthToken()
    linkedWalletRef.current = null
    lastWalletRef.current = null

    // FE-008: Clear service worker caches on logout to prevent stale
    // authenticated data from being served to the next user/session.
    try {
      if ('serviceWorker' in navigator) {
        const registrations = await navigator.serviceWorker.getRegistrations()
        for (const registration of registrations) {
          await registration.unregister()
        }
      }
      if ('caches' in window) {
        const cacheNames = await caches.keys()
        await Promise.all(cacheNames.map((name) => caches.delete(name)))
      }
    } catch (swErr) {
      console.warn('[Auth] Failed to clear SW caches on logout:', swErr)
    }

    // Re-establish anonymous session so RLS-dependent queries (browsing tasks,
    // public data) still work after logout. Without this, auth.uid() is null
    // and all RLS-gated queries silently return empty results.
    await supabase.auth.signOut()
    try {
      await supabase.auth.signInAnonymously()
    } catch (err) {
      console.warn('[Auth] Failed to re-init anonymous session after logout:', err)
    }
  }, [handleLogOut, setUserType])

  // --------------------------------------------------------------------------
  // Open auth modal
  // --------------------------------------------------------------------------
  const openAuthModal = useCallback(() => {
    // Don't open modal if already authenticated
    if (isAuthenticated && walletAddress) {
      return
    }
    // Don't open modal while SDK is still loading (may be restoring session)
    if (loading && !dynamicInitialized) {
      return
    }
    setShowAuthFlow(true)
  }, [isAuthenticated, walletAddress, loading, dynamicInitialized, setShowAuthFlow])

  // --------------------------------------------------------------------------
  // Effect: Track Dynamic.xyz initialization via sdkHasLoaded
  // No more race-prone setTimeout — we rely on the SDK's own readiness signal
  // --------------------------------------------------------------------------
  useEffect(() => {
    if (sdkHasLoaded && !dynamicInitialized) {
      setDynamicInitialized(true)
      console.log('[Auth] Dynamic SDK loaded, initialized')
    }
  }, [sdkHasLoaded, dynamicInitialized])

  // --------------------------------------------------------------------------
  // Effect: Auto-recover from broken auth state
  // If Dynamic says user is logged in but has no wallet (e.g., email OTP verified
  // but embedded wallet creation failed), auto-logout to clear the stale session.
  // Without this, users get stuck on "Link a wallet" with no way out.
  // --------------------------------------------------------------------------
  useEffect(() => {
    if (!dynamicInitialized || !isLoggedIn) return
    if (dynamicWalletAddress) return // Wallet exists — all good

    // Logged in but no wallet yet — email users wait for embedded wallet
    // creation (1-5s). Don't auto-logout; just stop the loading spinner
    // after 5s so the UI isn't stuck. The wallet-change effect (below)
    // will handle executor creation once the wallet arrives.
    const waitTimeout = setTimeout(() => {
      if (!dynamicWalletRef.current) {
        console.warn('[Auth] Logged in but no wallet after 5s — stopping loader (wallet may still arrive)')
        setLoading(false)
      }
    }, 5000)

    return () => clearTimeout(waitTimeout)
  }, [dynamicInitialized, isLoggedIn, dynamicWalletAddress])

  // --------------------------------------------------------------------------
  // Effect: Handle tab visibility changes (mobile tab switching)
  // When user switches away and comes back, re-fetch executor data to keep
  // the session warm. This helps after mobile browsers suspend the tab.
  // --------------------------------------------------------------------------
  useEffect(() => {
    if (typeof document === 'undefined') return

    const handleVisibilityChange = () => {
      if (document.visibilityState === 'visible' && walletAddress && dynamicInitialized) {
        console.log('[Auth] Tab restored — refreshing executor data')
        // Re-link wallet and refresh executor to keep Supabase session alive
        linkWalletToSession(walletAddress)
          .then(() => fetchExecutor(walletAddress))
          .then((data) => {
            if (data) setExecutor(data)
          })
          .catch((err) => console.warn('[Auth] Tab restore refresh failed:', err))
      }
    }

    document.addEventListener('visibilitychange', handleVisibilityChange)
    return () => document.removeEventListener('visibilitychange', handleVisibilityChange)
  }, [walletAddress, dynamicInitialized, linkWalletToSession, fetchExecutor])

  // --------------------------------------------------------------------------
  // Effect: Fetch executor when wallet changes
  // Note: dynamicWalletAddress is read via ref (not a dep) to prevent
  // unnecessary re-fetches when Dynamic SDK transitions wallet state
  // (e.g. null → address) while walletAddress stays the same via persisted fallback.
  // --------------------------------------------------------------------------
  useEffect(() => {
    if (!dynamicInitialized) {
      setLoading(true)
      return
    }

    if (walletAddress) {
      // Cancel any pending logout debounce — wallet is back
      if (logoutDebounceRef.current) {
        clearTimeout(logoutDebounceRef.current)
        logoutDebounceRef.current = null
      }

      localStorage.setItem(WALLET_STORAGE_KEY, walletAddress)
      setPersistedWalletAddress(walletAddress)
      lastWalletRef.current = walletAddress
      setLoading(true)

      // Safety timeout: if Supabase hangs (mobile Safari, slow network),
      // force loading=false after 10s so the app doesn't get stuck forever.
      loadingTimeoutRef.current = setTimeout(() => {
        console.warn('[Auth] Loading timeout — forcing loading=false')
        loadingTimeoutRef.current = null
        setLoading(false)
      }, 10_000)

      linkWalletToSession(walletAddress)
        .then(() => fetchExecutor(walletAddress, user?.email))
        .then((data) => {
          if (loadingTimeoutRef.current) {
            clearTimeout(loadingTimeoutRef.current)
            loadingTimeoutRef.current = null
          }
          // If we can't recover executor data for a persisted-only wallet,
          // clear persisted session and require explicit re-auth.
          if (!dynamicWalletRef.current && !data) {
            localStorage.removeItem(WALLET_STORAGE_KEY)
            setPersistedWalletAddress(null)
            setUserType(null)
          }
          setExecutor(data)
          setError(null) // Clear any previous error on successful load
          // Sync language preference from DB (cross-device persistence).
          // Updates localStorage + i18n only — does NOT write back to DB (avoids circular write).
          if (data?.preferred_language
            && SUPPORTED_LANGUAGES.includes(data.preferred_language as SupportedLanguage)
            && data.preferred_language !== getCurrentLanguage()) {
            localStorage.setItem('em-lang', data.preferred_language)
            i18nInstance.changeLanguage(data.preferred_language)
          }
          setLoading(false)
          // X OAuth enrichment: store X handle in social_links, auto-fill
          // display_name/avatar from X profile if generic. Non-blocking.
          if (data) {
            enrichFromX(data, walletAddress)
              .then((enriched) => {
                if (enriched) {
                  fetchExecutor(walletAddress).then((refreshed) => {
                    if (refreshed) setExecutor(refreshed)
                  }).catch(() => { /* non-critical */ })
                }
              })
              .catch(() => { /* non-critical, enrichment is best-effort */ })
          }
        })
        .catch((err) => {
          if (loadingTimeoutRef.current) {
            clearTimeout(loadingTimeoutRef.current)
            loadingTimeoutRef.current = null
          }
          console.error('[Auth] Failed to load executor:', err)
          setError(err instanceof Error ? err : new Error('Failed to connect wallet'))
          setExecutor(null)
          setLoading(false)
        })
    } else {
      // No wallet address. Two cases:
      // 1. User logged in via email, waiting for embedded wallet — DON'T clear
      // 2. User actually logged out — clear everything
      if (isLoggedIn) {
        // Email user waiting for embedded wallet — just stop loading
        setLoading(false)
      } else {
        // Actual logout — debounce and clear
        const debounceMs = /Mobi|Android|iPhone|iPad/i.test(navigator.userAgent) ? 2000 : 500
        logoutDebounceRef.current = setTimeout(() => {
          logoutDebounceRef.current = null
          setExecutor(null)
          setLoading(false)
          if (lastWalletRef.current) {
            lastWalletRef.current = null
            linkedWalletRef.current = null
            supabase.auth.signOut().catch((err: unknown) => {
              console.warn('[Auth] Failed to clear Supabase session:', err)
            })
          }
        }, debounceMs)
      }
    }

    return () => {
      if (logoutDebounceRef.current) {
        clearTimeout(logoutDebounceRef.current)
      }
      if (loadingTimeoutRef.current) {
        clearTimeout(loadingTimeoutRef.current)
        loadingTimeoutRef.current = null
      }
    }
  }, [dynamicInitialized, walletAddress, isLoggedIn, fetchExecutor, linkWalletToSession, setUserType, enrichFromX, user])

  // --------------------------------------------------------------------------
  // Context Value
  // --------------------------------------------------------------------------
  let value: AuthContextValue = {
    walletAddress,
    executor,
    userType,
    isAuthenticated,
    isProfileComplete,
    loading,
    error,
    logout,
    setUserType,
    refreshExecutor,
    openAuthModal,
  }

  // --------------------------------------------------------------------------
  // E2E Escape Hatch: Override auth state when __E2E_AUTH__ is present
  // All hooks have already been called above, so this is safe.
  // Only available in development mode to prevent production abuse.
  // --------------------------------------------------------------------------
  if (import.meta.env.DEV && typeof window !== 'undefined' && window.__E2E_AUTH__) {
    const e2e = window.__E2E_AUTH__
    value = {
      ...value,
      walletAddress: e2e.walletAddress,
      isAuthenticated: e2e.isAuthenticated,
      userType: e2e.role,
      isProfileComplete: true,
      loading: false,
      error: null,
      executor: {
        id: e2e.userId,
        user_id: e2e.userId,
        wallet_address: e2e.walletAddress,
        display_name: e2e.displayName || 'E2E Test User',
        bio: null,
        avatar_url: null,
        skills: [],
        languages: [],
        roles: [],
        email: null,
        phone: null,
        default_location: null,
        location_city: null,
        location_country: null,
        reputation_score: 85,
        tasks_completed: 10,
        tasks_disputed: 0,
        tasks_abandoned: 0,
        avg_rating: null,
        reputation_contract: null,
        reputation_token_id: null,
        erc8004_agent_id: null,
        agent_type: 'human' as const,
        networks_active: [],
        social_links: null,
        world_id_verified: false,
        world_id_level: null,
        world_human_id: null,
        world_verified_at: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        last_active_at: null,
      } as Executor,
    }
  }

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
}

// Re-export useAuth hook for backward compatibility
// Note: This re-export is needed for backward compatibility with existing imports
// eslint-disable-next-line react-refresh/only-export-components
export { useAuth } from './hooks'

