"""
Swarm Analytics — Metrics Aggregation & Trend Analysis
=======================================================

Provides production observability for the 24-agent swarm:
- Per-agent performance metrics (tasks completed, success rate, avg quality)
- Fleet-wide aggregations (active agents, total throughput, revenue)
- Trend analysis (7-day rolling averages, performance trajectories)
- Category heatmaps (which agents excel at which task types)
- Alert generation (degrading performance, stale agents, anomalies)

Architecture:
    SwarmRunner → Analytics.record_event() → Metrics stored
    Dashboard/MCP → Analytics.get_dashboard() → Aggregated view
    Cron/Heartbeat → Analytics.check_alerts() → Alert list

All data is in-memory with optional persistence to JSON files.
No external dependencies.
"""

import json
import time
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


# ──────────────────────────────────────────────────────────────
# Data Types
# ──────────────────────────────────────────────────────────────


@dataclass
class TaskEvent:
    """A recorded event from the swarm."""

    event_type: str  # "task_assigned", "task_completed", "task_failed", "task_expired"
    agent_id: str
    task_id: str
    category: str = ""
    bounty_usd: float = 0.0
    quality_rating: float = 0.0
    duration_seconds: float = 0.0
    timestamp: float = field(default_factory=time.time)
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "TaskEvent":
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class AgentMetrics:
    """Aggregated metrics for a single agent."""

    agent_id: str
    tasks_assigned: int = 0
    tasks_completed: int = 0
    tasks_failed: int = 0
    tasks_expired: int = 0
    total_revenue_usd: float = 0.0
    avg_quality: float = 0.0
    avg_duration_seconds: float = 0.0
    categories: dict = field(default_factory=dict)  # category → count
    last_active: float = 0.0
    quality_scores: list = field(default_factory=list)
    durations: list = field(default_factory=list)

    @property
    def success_rate(self) -> float:
        total = self.tasks_completed + self.tasks_failed + self.tasks_expired
        if total == 0:
            return 0.0
        return self.tasks_completed / total

    @property
    def is_active(self) -> bool:
        """Active if had activity in last 24 hours."""
        return (time.time() - self.last_active) < 86400

    @property
    def is_stale(self) -> bool:
        """Stale if no activity in 7+ days."""
        return self.last_active > 0 and (time.time() - self.last_active) > 604800

    def to_dict(self) -> dict:
        d = asdict(self)
        d["success_rate"] = round(self.success_rate, 4)
        d["is_active"] = self.is_active
        d["is_stale"] = self.is_stale
        return d


@dataclass
class FleetSnapshot:
    """Point-in-time snapshot of the entire fleet."""

    timestamp: float
    total_agents: int
    active_agents: int
    stale_agents: int
    total_tasks_completed: int
    total_tasks_failed: int
    total_revenue_usd: float
    avg_fleet_quality: float
    avg_success_rate: float
    top_categories: list  # [{"category": str, "count": int}]

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class Alert:
    """An alert generated by the analytics system."""

    level: str  # "info", "warning", "critical"
    agent_id: str  # "" for fleet-wide
    message: str
    metric: str
    value: float
    threshold: float
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        return asdict(self)


# ──────────────────────────────────────────────────────────────
# Analytics Engine
# ──────────────────────────────────────────────────────────────


class SwarmAnalytics:
    """
    Metrics aggregation and trend analysis for the agent swarm.

    Usage:
        analytics = SwarmAnalytics(storage_dir="/data/swarm/analytics")

        # Record events from SwarmRunner
        analytics.record_event(TaskEvent(
            event_type="task_completed",
            agent_id="agent_001",
            task_id="task_123",
            category="physical_verification",
            bounty_usd=5.00,
            quality_rating=4.8,
            duration_seconds=3600,
        ))

        # Get dashboard
        dashboard = analytics.get_dashboard()

        # Check for alerts
        alerts = analytics.check_alerts()
    """

    def __init__(
        self,
        storage_dir: Optional[str] = None,
        max_events: int = 10000,
        snapshot_interval_seconds: int = 3600,
    ):
        self._storage_dir = Path(storage_dir) if storage_dir else None
        self._max_events = max_events
        self._snapshot_interval = snapshot_interval_seconds

        # In-memory state
        self._events: list[TaskEvent] = []
        self._agent_metrics: dict[str, AgentMetrics] = {}
        self._snapshots: list[FleetSnapshot] = []
        self._last_snapshot_time: float = 0.0
        self._last_save_time: float = 0.0
        self._save_debounce_seconds: float = 30.0
        self._dirty: bool = False

        # Alert thresholds
        self._alert_thresholds = {
            "min_success_rate": 0.60,
            "min_quality": 2.5,
            "max_stale_days": 7,
            "min_fleet_active_pct": 0.25,
        }

        # Load persisted state
        if self._storage_dir:
            self._load_state()

    # ──────────────────────────────────────────────────────────
    # Event Recording
    # ──────────────────────────────────────────────────────────

    def record_event(self, event: TaskEvent) -> None:
        """Record a task event and update agent metrics."""
        self._events.append(event)

        # Enforce max events (FIFO)
        if len(self._events) > self._max_events:
            self._events = self._events[-self._max_events :]

        # Update agent metrics
        self._update_agent_metrics(event)

        # Auto-snapshot
        if time.time() - self._last_snapshot_time > self._snapshot_interval:
            self._take_snapshot()

        # Persist (debounced to avoid excessive I/O)
        self._dirty = True
        if self._storage_dir and (
            time.time() - self._last_save_time > self._save_debounce_seconds
        ):
            self._save_state()
            self._last_save_time = time.time()
            self._dirty = False

    def record_batch(self, events: list[TaskEvent]) -> int:
        """Record multiple events efficiently."""
        for event in events:
            self._events.append(event)
            self._update_agent_metrics(event)

        # Enforce max
        if len(self._events) > self._max_events:
            self._events = self._events[-self._max_events :]

        if time.time() - self._last_snapshot_time > self._snapshot_interval:
            self._take_snapshot()

        # Always save after batch (typically larger, less frequent)
        if self._storage_dir:
            self._save_state()
            self._last_save_time = time.time()

        return len(events)

    def flush(self) -> None:
        """Force-persist any dirty state to disk."""
        if self._storage_dir and self._dirty:
            self._save_state()
            self._last_save_time = time.time()
            self._dirty = False

    def _update_agent_metrics(self, event: TaskEvent) -> None:
        """Update per-agent metrics from an event."""
        agent_id = event.agent_id
        if agent_id not in self._agent_metrics:
            self._agent_metrics[agent_id] = AgentMetrics(agent_id=agent_id)

        m = self._agent_metrics[agent_id]
        m.last_active = max(m.last_active, event.timestamp)

        if event.event_type == "task_assigned":
            m.tasks_assigned += 1
        elif event.event_type == "task_completed":
            m.tasks_completed += 1
            m.total_revenue_usd += event.bounty_usd
            if event.quality_rating > 0:
                m.quality_scores.append(event.quality_rating)
                m.avg_quality = sum(m.quality_scores) / len(m.quality_scores)
            if event.duration_seconds > 0:
                m.durations.append(event.duration_seconds)
                m.avg_duration_seconds = sum(m.durations) / len(m.durations)
            # Category tracking
            cat = event.category or "unknown"
            m.categories[cat] = m.categories.get(cat, 0) + 1
        elif event.event_type == "task_failed":
            m.tasks_failed += 1
        elif event.event_type == "task_expired":
            m.tasks_expired += 1

    # ──────────────────────────────────────────────────────────
    # Dashboard & Queries
    # ──────────────────────────────────────────────────────────

    def get_dashboard(self) -> dict:
        """Get a complete fleet dashboard."""
        agents = list(self._agent_metrics.values())

        active = [a for a in agents if a.is_active]
        stale = [a for a in agents if a.is_stale]

        total_completed = sum(a.tasks_completed for a in agents)
        total_failed = sum(a.tasks_failed for a in agents)
        total_revenue = sum(a.total_revenue_usd for a in agents)

        quality_scores = [a.avg_quality for a in agents if a.avg_quality > 0]
        avg_quality = (
            sum(quality_scores) / len(quality_scores) if quality_scores else 0.0
        )

        success_rates = [
            a.success_rate for a in agents if a.tasks_completed + a.tasks_failed > 0
        ]
        avg_success = sum(success_rates) / len(success_rates) if success_rates else 0.0

        # Category heatmap
        category_totals = defaultdict(int)
        for a in agents:
            for cat, count in a.categories.items():
                category_totals[cat] += count
        top_cats = sorted(category_totals.items(), key=lambda x: x[1], reverse=True)[
            :10
        ]

        return {
            "timestamp": time.time(),
            "fleet": {
                "total_agents": len(agents),
                "active_agents": len(active),
                "stale_agents": len(stale),
                "idle_agents": len(agents) - len(active) - len(stale),
            },
            "performance": {
                "total_tasks_completed": total_completed,
                "total_tasks_failed": total_failed,
                "total_revenue_usd": round(total_revenue, 2),
                "avg_quality": round(avg_quality, 2),
                "avg_success_rate": round(avg_success, 4),
            },
            "categories": [{"category": c, "count": n} for c, n in top_cats],
            "top_agents": self._get_top_agents(5),
            "recent_events": len(self._events),
            "snapshots": len(self._snapshots),
        }

    def get_agent_detail(self, agent_id: str) -> Optional[dict]:
        """Get detailed metrics for a specific agent."""
        m = self._agent_metrics.get(agent_id)
        if not m:
            return None
        return m.to_dict()

    def get_all_agents(
        self, sort_by: str = "tasks_completed", limit: int = 50
    ) -> list[dict]:
        """Get all agents sorted by a metric."""
        agents = list(self._agent_metrics.values())

        sort_key = {
            "tasks_completed": lambda a: a.tasks_completed,
            "success_rate": lambda a: a.success_rate,
            "quality": lambda a: a.avg_quality,
            "revenue": lambda a: a.total_revenue_usd,
            "last_active": lambda a: a.last_active,
        }.get(sort_by, lambda a: a.tasks_completed)

        agents.sort(key=sort_key, reverse=True)
        return [a.to_dict() for a in agents[:limit]]

    def get_category_heatmap(self) -> dict:
        """Get agent × category performance matrix."""
        heatmap = {}
        for agent_id, m in self._agent_metrics.items():
            if m.categories:
                heatmap[agent_id] = dict(m.categories)
        return heatmap

    def _get_top_agents(self, n: int) -> list[dict]:
        """Get top N agents by composite score (completion × quality)."""
        scored = []
        for m in self._agent_metrics.values():
            score = (
                m.tasks_completed
                * (m.avg_quality / 5.0 if m.avg_quality > 0 else 0.5)
                * m.success_rate
            )
            scored.append((score, m))
        scored.sort(key=lambda x: x[0], reverse=True)
        return [
            {
                "agent_id": m.agent_id,
                "score": round(s, 2),
                "tasks": m.tasks_completed,
                "quality": round(m.avg_quality, 2),
                "success_rate": round(m.success_rate, 4),
            }
            for s, m in scored[:n]
        ]

    # ──────────────────────────────────────────────────────────
    # Trend Analysis
    # ──────────────────────────────────────────────────────────

    def get_trends(self, window_hours: int = 168) -> dict:
        """Get trend data for the last N hours (default: 7 days)."""
        cutoff = time.time() - (window_hours * 3600)
        recent = [e for e in self._events if e.timestamp >= cutoff]

        if not recent:
            return {"window_hours": window_hours, "events": 0, "trend": "no_data"}

        # Hourly buckets
        hourly = defaultdict(
            lambda: {"completed": 0, "failed": 0, "revenue": 0.0, "quality": []}
        )
        for e in recent:
            hour = int(e.timestamp // 3600) * 3600
            if e.event_type == "task_completed":
                hourly[hour]["completed"] += 1
                hourly[hour]["revenue"] += e.bounty_usd
                if e.quality_rating > 0:
                    hourly[hour]["quality"].append(e.quality_rating)
            elif e.event_type in ("task_failed", "task_expired"):
                hourly[hour]["failed"] += 1

        # Calculate trend direction
        hours_sorted = sorted(hourly.keys())
        if len(hours_sorted) >= 2:
            first_half = hours_sorted[: len(hours_sorted) // 2]
            second_half = hours_sorted[len(hours_sorted) // 2 :]

            first_completed = sum(hourly[h]["completed"] for h in first_half)
            second_completed = sum(hourly[h]["completed"] for h in second_half)

            if first_completed > 0:
                change = (second_completed - first_completed) / first_completed
                if change > 0.1:
                    trend = "improving"
                elif change < -0.1:
                    trend = "declining"
                else:
                    trend = "stable"
            else:
                trend = "growing" if second_completed > 0 else "flat"
        else:
            trend = "insufficient_data"

        # Daily rollups
        daily = defaultdict(lambda: {"completed": 0, "failed": 0, "revenue": 0.0})
        for e in recent:
            day = datetime.fromtimestamp(e.timestamp, tz=timezone.utc).strftime(
                "%Y-%m-%d"
            )
            if e.event_type == "task_completed":
                daily[day]["completed"] += 1
                daily[day]["revenue"] += e.bounty_usd
            elif e.event_type in ("task_failed", "task_expired"):
                daily[day]["failed"] += 1

        return {
            "window_hours": window_hours,
            "events": len(recent),
            "trend": trend,
            "daily": dict(daily),
            "total_completed": sum(hourly[h]["completed"] for h in hours_sorted),
            "total_failed": sum(hourly[h]["failed"] for h in hours_sorted),
            "total_revenue": round(sum(hourly[h]["revenue"] for h in hours_sorted), 2),
        }

    # ──────────────────────────────────────────────────────────
    # Alerts
    # ──────────────────────────────────────────────────────────

    def check_alerts(self) -> list[dict]:
        """Check for alert conditions across the fleet."""
        alerts = []

        # Per-agent alerts
        for agent_id, m in self._agent_metrics.items():
            total = m.tasks_completed + m.tasks_failed + m.tasks_expired
            if total < 3:
                continue  # Not enough data

            # Low success rate
            if m.success_rate < self._alert_thresholds["min_success_rate"]:
                alerts.append(
                    Alert(
                        level="warning",
                        agent_id=agent_id,
                        message=f"Agent {agent_id} success rate below threshold",
                        metric="success_rate",
                        value=m.success_rate,
                        threshold=self._alert_thresholds["min_success_rate"],
                    ).to_dict()
                )

            # Low quality
            if (
                m.avg_quality > 0
                and m.avg_quality < self._alert_thresholds["min_quality"]
            ):
                alerts.append(
                    Alert(
                        level="warning",
                        agent_id=agent_id,
                        message=f"Agent {agent_id} quality below threshold",
                        metric="avg_quality",
                        value=m.avg_quality,
                        threshold=self._alert_thresholds["min_quality"],
                    ).to_dict()
                )

            # Stale agent
            if m.is_stale:
                days_inactive = (time.time() - m.last_active) / 86400
                alerts.append(
                    Alert(
                        level="info",
                        agent_id=agent_id,
                        message=f"Agent {agent_id} inactive for {days_inactive:.1f} days",
                        metric="days_inactive",
                        value=days_inactive,
                        threshold=self._alert_thresholds["max_stale_days"],
                    ).to_dict()
                )

        # Fleet-wide alerts
        total_agents = len(self._agent_metrics)
        if total_agents > 0:
            active_pct = (
                sum(1 for m in self._agent_metrics.values() if m.is_active)
                / total_agents
            )
            if active_pct < self._alert_thresholds["min_fleet_active_pct"]:
                alerts.append(
                    Alert(
                        level="critical",
                        agent_id="",
                        message=f"Fleet activity below threshold: {active_pct:.0%} active",
                        metric="fleet_active_pct",
                        value=active_pct,
                        threshold=self._alert_thresholds["min_fleet_active_pct"],
                    ).to_dict()
                )

        return alerts

    def set_alert_threshold(self, metric: str, value: float) -> None:
        """Update an alert threshold."""
        if metric in self._alert_thresholds:
            self._alert_thresholds[metric] = value

    # ──────────────────────────────────────────────────────────
    # Snapshots
    # ──────────────────────────────────────────────────────────

    def _take_snapshot(self) -> FleetSnapshot:
        """Take a point-in-time snapshot of fleet state."""
        agents = list(self._agent_metrics.values())
        active = [a for a in agents if a.is_active]
        stale = [a for a in agents if a.is_stale]

        quality_scores = [a.avg_quality for a in agents if a.avg_quality > 0]
        success_rates = [
            a.success_rate for a in agents if a.tasks_completed + a.tasks_failed > 0
        ]

        category_totals = defaultdict(int)
        for a in agents:
            for cat, count in a.categories.items():
                category_totals[cat] += count
        top_cats = sorted(category_totals.items(), key=lambda x: x[1], reverse=True)[:5]

        snapshot = FleetSnapshot(
            timestamp=time.time(),
            total_agents=len(agents),
            active_agents=len(active),
            stale_agents=len(stale),
            total_tasks_completed=sum(a.tasks_completed for a in agents),
            total_tasks_failed=sum(a.tasks_failed for a in agents),
            total_revenue_usd=round(sum(a.total_revenue_usd for a in agents), 2),
            avg_fleet_quality=round(
                sum(quality_scores) / len(quality_scores) if quality_scores else 0, 2
            ),
            avg_success_rate=round(
                sum(success_rates) / len(success_rates) if success_rates else 0, 4
            ),
            top_categories=[{"category": c, "count": n} for c, n in top_cats],
        )

        self._snapshots.append(snapshot)
        self._last_snapshot_time = time.time()

        # Keep last 720 snapshots (30 days at hourly)
        if len(self._snapshots) > 720:
            self._snapshots = self._snapshots[-720:]

        return snapshot

    def get_snapshots(self, limit: int = 24) -> list[dict]:
        """Get recent fleet snapshots."""
        return [s.to_dict() for s in self._snapshots[-limit:]]

    # ──────────────────────────────────────────────────────────
    # Persistence
    # ──────────────────────────────────────────────────────────

    def _save_state(self) -> None:
        """Persist analytics state to disk."""
        if not self._storage_dir:
            return

        self._storage_dir.mkdir(parents=True, exist_ok=True)

        state = {
            "version": 1,
            "saved_at": time.time(),
            "events_count": len(self._events),
            "agents": {k: v.to_dict() for k, v in self._agent_metrics.items()},
            "snapshots": [s.to_dict() for s in self._snapshots[-100:]],
            "alert_thresholds": self._alert_thresholds,
        }

        # Atomic write
        tmp_path = self._storage_dir / "analytics_state.tmp"
        final_path = self._storage_dir / "analytics_state.json"

        with open(tmp_path, "w") as f:
            json.dump(state, f, indent=2)
        tmp_path.rename(final_path)

    def _load_state(self) -> None:
        """Load persisted analytics state."""
        if not self._storage_dir:
            return

        state_path = self._storage_dir / "analytics_state.json"
        if not state_path.exists():
            return

        try:
            with open(state_path) as f:
                state = json.load(f)

            if state.get("version") != 1:
                return

            # Restore agent metrics
            for agent_id, data in state.get("agents", {}).items():
                m = AgentMetrics(agent_id=agent_id)
                m.tasks_assigned = data.get("tasks_assigned", 0)
                m.tasks_completed = data.get("tasks_completed", 0)
                m.tasks_failed = data.get("tasks_failed", 0)
                m.tasks_expired = data.get("tasks_expired", 0)
                m.total_revenue_usd = data.get("total_revenue_usd", 0.0)
                m.avg_quality = data.get("avg_quality", 0.0)
                m.avg_duration_seconds = data.get("avg_duration_seconds", 0.0)
                m.categories = data.get("categories", {})
                m.last_active = data.get("last_active", 0.0)
                m.quality_scores = data.get("quality_scores", [])
                m.durations = data.get("durations", [])
                self._agent_metrics[agent_id] = m

            # Restore snapshots
            for snap_data in state.get("snapshots", []):
                self._snapshots.append(
                    FleetSnapshot(
                        **{
                            k: v
                            for k, v in snap_data.items()
                            if k in FleetSnapshot.__dataclass_fields__
                        }
                    )
                )

            # Restore thresholds
            if "alert_thresholds" in state:
                self._alert_thresholds.update(state["alert_thresholds"])

        except (json.JSONDecodeError, KeyError, TypeError):
            pass  # Corrupted state, start fresh

    # ──────────────────────────────────────────────────────────
    # Utilities
    # ──────────────────────────────────────────────────────────

    def reset(self) -> None:
        """Reset all analytics state."""
        self._events.clear()
        self._agent_metrics.clear()
        self._snapshots.clear()
        self._last_snapshot_time = 0.0

    @property
    def event_count(self) -> int:
        return len(self._events)

    @property
    def agent_count(self) -> int:
        return len(self._agent_metrics)

    def summary(self) -> str:
        """One-line summary for logging."""
        d = self.get_dashboard()
        f = d["fleet"]
        p = d["performance"]
        return (
            f"Fleet: {f['active_agents']}/{f['total_agents']} active | "
            f"Tasks: {p['total_tasks_completed']} done, {p['total_tasks_failed']} failed | "
            f"Quality: {p['avg_quality']:.1f}/5 | "
            f"Revenue: ${p['total_revenue_usd']:.2f}"
        )
