/**
 * X (Twitter) Profile Enrichment Hook
 *
 * After Dynamic.xyz authentication, checks if the user has an X OAuth
 * credential and automatically:
 * 1. Stores the X handle in social_links via the backend API
 * 2. Auto-fills display_name from X profile if the current name is auto-generated
 * 3. Auto-fills avatar_url from X profile photo if empty
 *
 * Only updates empty/generic fields -- never overwrites user-set data.
 */

import { useCallback, useRef } from 'react'
import { useDynamicContext } from '@dynamic-labs/sdk-react-core'
import type { JwtVerifiedCredential } from '@dynamic-labs/sdk-api-core'
import { supabase } from '../lib/supabase'
import { isAutoGeneratedName } from '../utils/profileUtils'
import type { Executor } from '../types/database'

const API_BASE_URL = (import.meta.env.VITE_API_URL || 'https://api.execution.market').replace(/\/+$/, '')

function findXCredential(
  verifiedCredentials: JwtVerifiedCredential[] | undefined
): JwtVerifiedCredential | null {
  if (!verifiedCredentials?.length) return null
  return (
    verifiedCredentials.find(
      (c) => c.oauthProvider === 'twitter' && c.format === 'oauth'
    ) ?? null
  )
}

async function getAccessToken(): Promise<string | null> {
  const { data } = await supabase.auth.getSession()
  return data.session?.access_token ?? null
}

export function useXProfileEnrichment() {
  const { user } = useDynamicContext()
  const enrichedRef = useRef<string | null>(null)

  const enrichFromX = useCallback(
    async (executor: Executor, walletAddress: string): Promise<boolean> => {
      // Only enrich once per session per wallet
      if (enrichedRef.current === walletAddress) return false

      const xCred = findXCredential(user?.verifiedCredentials as JwtVerifiedCredential[] | undefined)
      if (!xCred?.oauthUsername) return false

      enrichedRef.current = walletAddress
      const handle = `@${xCred.oauthUsername}`
      let changed = false

      try {
        // 1. Store X handle in social_links via API
        const token = await getAccessToken()
        if (token) {
          const existingHandle = executor.social_links?.x?.handle
          if (existingHandle !== handle) {
            await fetch(`${API_BASE_URL}/api/v1/workers/social-links`, {
              method: 'PUT',
              headers: {
                'Content-Type': 'application/json',
                Authorization: `Bearer ${token}`,
              },
              body: JSON.stringify({ platform: 'x', handle }),
            })

            // Mark as verified (OAuth-verified) + store user_id via direct DB update
            const xUserId = xCred.oauthAccountId
            if (xUserId) {
              await supabase
                .from('executors')
                .update({
                  social_links: {
                    ...executor.social_links,
                    x: {
                      handle,
                      verified: true,
                      user_id: xUserId,
                      linked_at: new Date().toISOString(),
                    },
                  },
                })
                .eq('wallet_address', walletAddress.toLowerCase())
            }
            changed = true
          }
        }

        // 2. Auto-fill display_name if generic
        if (
          executor.display_name &&
          isAutoGeneratedName(executor.display_name) &&
          xCred.oauthDisplayName
        ) {
          await supabase
            .from('executors')
            .update({ display_name: xCred.oauthDisplayName })
            .eq('wallet_address', walletAddress.toLowerCase())
          changed = true
        }

        // 3. Auto-fill avatar if empty
        const photos = (xCred as unknown as Record<string, unknown>).oauthAccountPhotos as string[] | undefined
        if (!executor.avatar_url && photos?.[0]) {
          await supabase
            .from('executors')
            .update({ avatar_url: photos[0] })
            .eq('wallet_address', walletAddress.toLowerCase())
          changed = true
        }
      } catch (err) {
        console.warn('[XEnrich] Non-critical enrichment error:', err)
      }

      return changed
    },
    [user]
  )

  return { enrichFromX }
}
